version: 2.1  # Specifies the CircleCI configuration version

jobs:
  build_and_test:  # Define a job for building and testing the app
    docker:
      - image: cimg/android:2024.01  # Use a pre-built Android image

    steps:
      - checkout  # Check out the source code

      - restore_cache:  # Restore cached dependencies to speed up builds
          keys:
            - android-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}
            - android-dependencies-

      - run:
          name: Set local.properties
          command: echo "sdk.dir=$ANDROID_HOME" > local.properties

      - run:
          name: Download Dependencies
          command: |
            ./gradlew androidDependencies  # Download project dependencies

      - save_cache:  # Save dependencies to cache for faster future builds
          paths:
            - ~/.gradle/caches
          key: android-dependencies-{{ checksum "build.gradle" }}-{{ checksum "app/build.gradle" }}

      - run:
          name: Run Unit Tests
          command: |
            ./gradlew testDebugUnitTest  # Run unit tests

      - run:
          name: Build Debug APK
          command: |
            ./gradlew assembleDebug  # Build the debug APK

      - store_artifacts:  # Store the built APK as an artifact
          path: app/build/outputs/apk/debug/app-debug.apk

workflows:
  version: 2  # Defines the workflow version
  build_workflow:  # Define a workflow to run the job
    jobs:
      - build_and_test  # Include the defined job in the workflow